export default {
  SHIFT_COLOR_THEME: 'shifty.shiftColorTheme',
  SHIFT_FONT_FAMILY: 'shifty.shiftFontFamily',
  SHIFT_BOTH: 'shifty.shiftBoth',
  FAVORITE_COLOR_THEME: 'shifty.favoriteColorTheme',
  FAVORITE_FONT_FAMILY: 'shifty.favoriteFontFamily',
  FAVORITE_BOTH: 'shifty.favoriteBoth',
  IGNORE_COLOR_THEME: 'shifty.ignoreColorTheme',
  IGNORE_FONT_FAMILY: 'shifty.ignoreFontFamily',
  IGNORE_BOTH: 'shifty.ignoreBoth',
  START_SHIFT_INTERVAL: 'shifty.startShiftInterval',
  PAUSE_SHIFT_INTERVAL: 'shifty.pauseShiftInterval',
  SHOW_STATUS: 'shifty.showStatus',
  ENABLE_DEBUGGING: 'shifty.enableDebugging',
}
